### PR TITLE
Windows fixes

### LINKED ISSUE #74: The process with PID could not be terminated. The operation attempted is not supported.
Sometimes the ES instance on Windows can't be killed, and the build fails :-(

May be related to an [unkillable state](https://blogs.technet.microsoft.com/markrussinovich/2005/08/17/unkillable-processes/).

```
[INFO] com.github.alexcojocaru.mojo.elasticsearch.v2.ElasticsearchSetupException: Elasticsearch [0]: Cannot execute command '[taskkill, /F, /pid, 12340]' in directory 'C:\Projects\elasticsearch-maven-plugin\target\it\runforked-with-path-conf\target\elasticsearch0'
[INFO] Output:
[INFO]
[INFO] Error:
[INFO] ERROR: The process with PID 12340 could not be terminated.
[INFO] Reason: The operation attempted is not supported.
[INFO]
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:267)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:149)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.terminateWindowsProcess(ForkedElasticsearchProcessDestroyer.java:118)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.terminateProcess(ForkedElasticsearchProcessDestroyer.java:65)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.access$000(ForkedElasticsearchProcessDestroyer.java:15)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer$1.run(ForkedElasticsearchProcessDestroyer.java:28)
[INFO] Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[INFO]  at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
[INFO]  at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:222)
[INFO]  ... 5 more
```

### PR DESCRIPTION
**Pull request by rustyx**
Fixes #74 and #75.

### CODE REVIEW

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedInstance.java [hunk 1]
```diff
@@ -39,7 +39,7 @@ public void run()
 
         ProcessUtil.executeScript(config,
                 getStartScriptCommand(),
-                null,
+                ProcessUtil.createEnvironment(null),
```
Comment (alexcojocaru) [inline src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedInstance.java]: As far as I can tell, this change will not result in any different behavior anywhere in the call stack.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java [hunk 2]
```diff
@@ -316,6 +328,11 @@ public static boolean isWindowsProcessAlive(InstanceConfiguration config, String
         // and unsets these. And because the scripts would print a warning, we can't rely on the output :(
         result.remove("JAVA_TOOL_OPTIONS");
         result.remove("JAVA_OPTS");
+        // the following environment variables may interfere with the elasticsearch instance.
+        result.remove("ES_HOME");
+        result.remove("ES_JAVA_OPTS");
```
Comment (alexcojocaru) [inline src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java]: If the ES_JAVA_OPTS was set in InstallPluginsStep:28 (through a plugin config param), this line will remove that setting.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/step/InstallPluginsStep.java [hunk 3]
```diff
@@ -54,7 +54,7 @@ public void execute(InstanceConfiguration config)
                     .addArgument("--batch")
                     .addArgument(plugin.getUri());
             
-            ProcessUtil.executeScript(config, cmd, environment, null);
+            ProcessUtil.executeScript(config, cmd, ProcessUtil.createEnvironment(environment), null);
```
Comment (alexcojocaru) [inline src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/step/InstallPluginsStep.java]: I don't understand this change either. If you want those vars to be removed from the env, that's is done anyway (for ProcessUtil.executeScript always calls ProcessUtils.createEnvironment to build the env).

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java [hunk 4]
```diff
@@ -76,6 +76,18 @@ public static CommandLine buildKillCommandLine(String pid)
...
         return command;
     }
+    
+    /**
+     * After forcibly killing the ES instance, remove the pid file.
+     * @param baseDir the base directory where the pid file is
+     */
+    public static void cleanupPid(String baseDir)
+    {
+        if (SystemUtils.IS_OS_WINDOWS)
```
Comment (alexcojocaru) [inline src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java]: Wondering why you want the pid file delete to be done only on Win.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java [hunk 5]
```diff
@@ -113,29 +113,45 @@ private void terminateWindowsProcess(InstanceConfiguration config)
...
+                            /* ignore */
+                        }
+                    }
+                    log.error(String.format(
+                            "Error while destroying the Elasticsearch process [%d]",
+                            config.getId()),
+                            e);
+                }
             }
+            break;
```
Comment (alexcojocaru) [inline src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java]: can you move the `break` to the end of the if block (right after removing the pid file), to make the method more readable?

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java [hunk 6]
```diff
@@ -113,29 +113,45 @@ private void terminateWindowsProcess(InstanceConfiguration config)
...
+                }
+                else
+                {
+                    // sometimes taskkill fails with "The operation attempted is not supported."
+                    // https://blogs.technet.microsoft.com/markrussinovich/2005/08/17/unkillable-processes/
+                    // in that case, retry
+                    if (retry < 2) {
+                        try {
+                            Thread.sleep(500);
+                            continue;
```
Comment (alexcojocaru) [inline src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java]: On 1st and 2nd attempt, if the sleep fails, the kill will not be retried (the `continue` will be skipped, and the catch block will be executed instead). Is this what you wanted?

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java (hunk 4 above)
Comment (rustyx) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java]: That's because on *NIX `Process.destroy()` sends a SIGTERM, so ES gets the chance to do proper cleanup. On Win, a force-kill is done and ES cannot cleanup anything.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java (hunk 5 above)
Comment (rustyx) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java]: It's more readable this way actually. The `break` is at the end of the loop. Otherwise it would have to be in 3 places.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java (hunk 6 above)
Comment (rustyx) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java]: The only reason for `Thread.sleep()` to fail is when `interrupt()` is called by another thread. In that case we want to exit asap. So yes it's what I wanted.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java (hunk 2 above)
Comment (rustyx) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java]: Missed that bit, sorry. Will fix.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java (hunk 6 above)
Comment (alexcojocaru) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java]: :+1:

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java (hunk 5 above)
Comment (alexcojocaru) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java]: You are correct; ignore  my comment.

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java (hunk 4 above)
Comment (alexcojocaru) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java]: I thought I made a comment about the `/f` flag on taskkill, but most probably it wasn't published it since I cannot find it.
Anyway, I was asking if we should rather remove the `/f` flag (which stands for force, similar to SIGKILL on linux) from taskkill; that would give the ES process the chance to shut down nicely. If so, then we don't need the pid file deletion (or it can stay, to catch the cases where the file doesn't get removed).

File: src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java (hunk 2 above)
Comment (alexcojocaru) [reply src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ProcessUtil.java]: Maybe a better approach is to remove the troublesome env vars before setting whichever vars (eg. ES_JAVA_OPTS) were set on the plugin config.
